version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: proy2
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: quetzalshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/views.sql:/docker-entrypoint-initdb.d/02_views.sql
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/03_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U proy2 -d quetzalshop_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  postgres_data:
